
import React from "react";

export const organHealthData = [
    {
      name: "Heart",
      healthScore: 95,
      status: "Healthy",
      sourceOfAnalysis: "Based on: Your last Lipid Profile, BMI, and Blood Pressure readings.",
      recommendations: ["Continue your healthy lifestyle and regular check-ups."],
      icon: "Heart",
      image: "https://picsum.photos/seed/heart/100/100",
      dataAiHint: "heart organ",
      color: "hsl(var(--nav-emergency))",
    },
    {
      name: "Liver",
      healthScore: 88,
      status: "Needs Monitoring",
      sourceOfAnalysis: "Based on: Your Liver Function Test from Sep 2023, which showed slightly elevated enzymes.",
      recommendations: ["Consider a follow-up Liver Function Test in 30 days.", "Reduce intake of processed foods and alcohol."],
      icon: "Leaf",
      image: "https://picsum.photos/seed/liver/100/100",
      dataAiHint: "liver organ",
      color: "hsl(var(--nav-diagnostics))",
    },
    {
      name: "Kidneys",
      healthScore: 90,
      status: "Good",
      sourceOfAnalysis: "Based on: Your recent Urinalysis and Serum Creatinine levels, which are in the normal range.",
      recommendations: ["Stay well-hydrated by drinking plenty of water throughout the day."],
      icon: "Droplets",
      image: "https://picsum.photos/seed/kidneys/100/100",
      dataAiHint: "kidneys organ",
      color: "hsl(var(--nav-chat))",
    },
    {
      name: "Lungs",
      healthScore: 92,
      status: "Good",
      sourceOf_analysis: "Based on: Your recent Chest X-Ray, which was clear.",
      recommendations: ["Avoid exposure to smoke and pollutants.", "Practice deep breathing exercises."],
      icon: "Wind",
      image: "https://picsum.photos/seed/lungs/100/100",
      dataAiHint: "lungs organ",
      color: "hsl(var(--nav-junior-doctors))",
    },
    {
      name: "Brain",
      healthScore: null,
      status: "Needs Critical Attention",
      sourceOfAnalysis: "Based on: Doctor's notes mentioning 'episodes of confusion (encephalopathy)' on Jul 10, 2024.",
      recommendations: ["Your doctor has referred you to the transplant team. It is important to follow up on this recommendation immediately."],
      icon: "Brain",
      image: "https://picsum.photos/seed/brain/100/100",
      dataAiHint: "brain organ",
      color: "hsl(var(--nav-symptoms))",
    },
    {
        name: "Stomach (Gut)",
        healthScore: 93,
        status: "Healthy",
        sourceOfAnalysis: "Based on: Your recent CT Scan of the abdomen, which was normal.",
        recommendations: ["Maintain a balanced diet rich in fiber."],
        icon: "Activity",
        image: "https://picsum.photos/seed/stomach/100/100",
        dataAiHint: "stomach organ",
        color: "hsl(var(--nav-medicines))",
    }
];
